"""Adding conversations tables AGAIN

Revision ID: 215c0451614f
Revises: 
Create Date: 2025-03-25 11:10:38.532166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215c0451614f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('read', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('recipient_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('conversation_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_message_timestamp'), ['timestamp'], unique=False)
        batch_op.create_foreign_key("fk_conversation_id", 'conversation', ['conversation_id'], ['id'])
        batch_op.create_foreign_key("fk_sender_id", 'users', ['sender_id'], ['id'])
        batch_op.create_foreign_key("fk_recipient_id", 'users', ['recipient_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_message_timestamp'))
        batch_op.drop_column('conversation_id')
        batch_op.drop_column('recipient_id')
        batch_op.drop_column('sender_id')
        batch_op.drop_column('read')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('content')

    # ### end Alembic commands ###
